spring:
  # Database:
  datasource:
    url: jdbc:postgresql://localhost:5432/market
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  # JPA properties:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  # Cash
  cache:
    type: simple
    cache-names: products



